- name: iptables start
  service: name=netfilter-persistent state=started enabled=yes
  become: yes

- name: iptables save
  shell: service netfilter-persistent save
  become: yes
  notify: iptables start

