---
#- name: Configure Apache.
#  lineinfile:
#    dest: "{{ apache_server_root }}/ports.conf"
#    regexp: "{{ item.regexp }}"
#    line: "{{ item.line }}"
#    state: present
#  with_items: "{{ apache_ports_configuration_items }}"
#  notify: restart apache

- name: create directory for apache2 
  become: yes
  file: >
    path="{{ apache_server_root }}"
    owner=root
    group=root
    mode=0750
    state=directory

- name: copy ports.conf
  become: yes
  copy: >
    src="ports.conf"
    dest="{{ apache_server_root }}/ports.conf"
    owner=root
    group=root

- name: copy security.conf
  become: yes
  copy: >
    src="security.conf"
    dest="{{ apache_server_root }}/conf-available/security.conf"
    owner=root
    group=root

- name: create directory for ssl 
  become: yes
  file: >
    path="{{ apache_server_root }}/ssl"
    owner=root
    group=root
    mode=0750
    state=directory

- name: copy ssl cert
  become: yes
  copy: >
    src="{{ apache2_proxy_crt }}"
    dest="{{ apache_server_root }}/{{ apache2_proxy_crt }}"
    owner=root
    group=root
  when: apache2_proxy_crt is defined

- name: copy ssl key
  become: yes
  copy: >
    src="{{ apache2_proxy_key }}"
    dest="{{ apache_server_root }}/{{ apache2_proxy_key }}"
    owner=root
    group=root
  when: apache2_proxy_key is defined

- name: Enable Apache mods.
  file:
    src: "{{ apache_server_root }}/mods-available/{{ item }}"
    dest: "{{ apache_server_root }}/mods-enabled/{{ item }}"
    state: link
  with_items: "{{ apache_mods_enabled }}"
  notify: restart apache

- name: Disable Apache mods.
  file:
    path: "{{ apache_server_root }}/mods-enabled/{{ item }}"
    state: absent
  with_items: "{{ apache_mods_disabled }}"
  notify: restart apache

- name: Check whether certificates defined in vhosts exist.
  stat: "path={{ item.certificate_file }}"
  register: apache_ssl_certificates
  with_items: "{{ apache_vhosts_ssl }}"

- name: Add apache vhosts configuration.
  template:
    src: "vhosts.conf.j2"
    dest: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts

- name: Add vhost symlink in sites-enabled.
  file:
    src: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    dest: "{{ apache_conf_path }}/sites-enabled/{{ apache_vhosts_filename }}"
    state: link
  notify: restart apache
  when: apache_create_vhosts

- name: Remove default vhost in sites-enabled.
  file:
    path: "{{ apache_conf_path }}/sites-enabled/{{ apache_default_vhost_filename }}"
    state: absent
  notify: restart apache
  when: apache_remove_default_vhost
