- name: Keep temporary old hostname in /etc/hosts
  become: yes
  lineinfile:
    dest=/etc/hosts
    regexp="^127\.0\.1\.1(.*)"
    line="127.0.1.1{{'\t'}}{{inventory_hostname.split('.').0}}{% if inventory_hostname.split('.').0 != inventory_hostname %}{{'\t'}}{{inventory_hostname}}{% endif %}\1"
    state=present
    backup=yes
    backrefs=yes
  when: ansible_hostname != inventory_hostname.split('.').0
  tags:
    - configuration
    - hostname

- name: Set hostname
  become: yes
  hostname: name={{inventory_hostname.split('.').0}}
  tags:
    - configuration
    - hostname

- name: Update /etc/hosts
  become: yes
  lineinfile:
    dest=/etc/hosts
    regexp="^127\.0\.1\.1"
    line="127.0.1.1{{'\t'}}{{inventory_hostname.split('.').0}}{% if inventory_hostname.split('.').0 != inventory_hostname %}{{'\t'}}{{inventory_hostname}}{% endif %}"
    state=present
  tags:
    - configuration
    - hostname
